
     <?php
define('TITLE', 'Room');
define('PAGE', 'room');
include('header.php'); 
?> 
     <!-- Begin Page Content -->
                    <div class="container-fluid">

                        <!-- Page Heading -->
                        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                            <h1 class="h3 mb-0 text-gray-800">Rooms</h1>
                        </div>

                        <!-- add stud -->
                        <div class="row mb-3">

                            <button type="button" class="btn btn-success">
                                <i class="fas fa-plus-square"></i>
                                Add Rooms</button>

                        </div>

                        <!-- Content Row -->
                        
                            <table class="table roomTable">
                                <thead>
                                    <th>Hostel Name</th>
                                    <th>ROOM No</th>
                                    <th>Room Type</th>
                                    <th>status</th>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>9</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>9</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>20</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>37</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>45</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>28</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>6</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>44</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>37</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>53</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>52</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>43</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>32</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>2</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>57</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>34</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>20</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>39</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>56</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>33</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>35</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>9</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>52</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>6</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>24</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>60</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>56</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>21</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>6</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>20</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>34</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>53</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>22</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>35</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>39</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>52</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>48</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>41</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>21</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>35</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>43</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>50</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>55</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>57</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>15</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>41</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>59</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>12</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>59</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>17</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>24</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>33</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>14</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>25</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>49</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>33</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>2</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>38</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>47</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>32</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>39</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>10</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>33</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>4</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>53</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>53</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>44</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>8</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>45</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>38</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>44</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>56</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>7</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>42</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>31</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>5</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>11</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>52</td>
                                        <td>Double</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>49</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>37</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>12</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>47</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>54</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>33</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>30</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>24</td>
                                        <td>Double</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>17</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>54</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>46</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>37</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>15</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>60</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>60</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>17</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>44</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>30</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH1</td>
                                        <td>30</td>
                                        <td>Single</td>
                                        <td>OPEN</td>
                                    </tr>
                                    <tr>
                                        <td>JBH2</td>
                                        <td>7</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                    <tr>
                                        <td>JBH3</td>
                                        <td>34</td>
                                        <td>Single</td>
                                        <td>Occupied</td>
                                    </tr>
                                </tbody>
                            </table>
<?php include('footer.php') ?>